name: "Github Actions Mobsuccess"
description: "Github Mobsuccess Compliance"
inputs:
  action:
    description: "The action to be performed: validate-pr or after-pr-merged"
    required: false
  github-token:
    description: "your github auth token"
    required: false
  amplify-uri:
    description: "the AWS Amplify URI template"
    required: false
  storybook-amplify-uri:
    description: "the AWS Amplify Storybook URI template"
    required: false
branding:
  icon: "chevron-right"
  color: "gray-dark"
runs:
  using: "node12"
  main: "index.js"
