name: "Github Actions Mobsuccess"
description: "Github Mobsuccess Compliance"
inputs:
  action:
    description: "The action to be performed: validate-pr or changelog"
    required: false
  github-token:
    description: "your github auth token"
    required: false
  amplify-uri:
    description: "the AWS Amplify URI template"
    required: false
  storybook-amplify-uri:
    description: "the AWS Amplify Storybook URI template"
    required: false
  unreleased-tag:
    description: "Latest unreleased (yet) tag for which to generate changelog"
    required: false
  max-releases:
    description: "The number of releases for which to generate a changelog"
    required: false
outputs:
  changelog:
    description: "The generated changelog"
branding:
  icon: "chevron-right"
  color: "gray-dark"
runs:
  using: "node12"
  main: "index.js"
