const AI_TOOLS = [
  "Claude",
  "Claude Code",
  "Claude Opus",
  "Claude Sonnet",
  "Anthropic",

  "ChatGPT",
  "GPT-4",
  "GPT-4o",
  "GPT-3",
  "OpenAI",
  "Codex",
  "o1",
  "o3",

  "Copilot",
  "GitHub Copilot",
  "Copilot Chat",
  "Copilot Workspace",

  "Gemini",
  "Gemini Code Assist",
  "Bard",
  "Google AI",
  "Duet AI",

  "Cursor",
  "Windsurf",
  "Codeium",
  "Continue",
  "Continue.dev",

  "Tabnine",
  "Augment",
  "Augment Code",
  "Sourcegraph Cody",
  "Cody",

  "JetBrains AI",
  "AI Assistant",

  "Aider",
  "Cline",
  "Claude Engineer",
  "GPT Engineer",
  "Devin",
  "Auto-GPT",
  "AutoGPT",
  "AgentGPT",
  "BabyAGI",
  "MetaGPT",

  "CodeGPT",
  "CodeWhisperer",
  "Amazon Q",
  "Replit AI",
  "Ghostwriter",
  "Codey",
  "StarCoder",
  "Code Llama",
  "CodeLlama",
  "WizardCoder",
  "Phind",
  "Blackbox AI",
  "AskCodi",

  "Perplexity",
];

const escapeRegex = (str) => str.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
const AI_TOOLS_PATTERN = AI_TOOLS.map(escapeRegex).join("|");

const AI_DOMAINS = ["@anthropic.com", "@openai.com"];

const GENAI_BOT_PATTERNS = [
  /copilot\[bot\]/i,
  /claude\[bot\]/i,
  /anthropic\[bot\]/i,
  /openai\[bot\]/i,
  /chatgpt\[bot\]/i,
  /cursor\[bot\]/i,
  /codeium\[bot\]/i,
  /tabnine\[bot\]/i,
  /cody\[bot\]/i,
  /devin\[bot\]/i,
  /aider\[bot\]/i,
];

const AUTOMATION_BOT_PATTERNS = [
  /github-actions\[bot\]/i,
  /dependabot\[bot\]/i,
  /renovate\[bot\]/i,
  /semantic-release-bot/i,
  /greenkeeper\[bot\]/i,
  /snyk-bot/i,
  /codecov\[bot\]/i,
  /netlify\[bot\]/i,
  /vercel\[bot\]/i,
  /allcontributors\[bot\]/i,
  /imgbot\[bot\]/i,
  /mergify\[bot\]/i,
  /stale\[bot\]/i,
  /pull\[bot\]/i,
];

const COMMIT_PATTERNS = [
  /Generated with Claude Code/i,
  new RegExp(`🤖\\s*Generated with \\[Claude Code\\]`, "i"),

  new RegExp(`co[- ]?authored[- ]?by[:\\s].*\\b(${AI_TOOLS_PATTERN})\\b`, "i"),
  /co[- ]?authored[- ]?by[:\s].*(@anthropic\.com|@openai\.com)/i,

  /Generated by (AI|LLM)/i,
  /AI-generated/i,
  /\[AI\]/i,
  /\[GenAI\]/i,

  /\[Copilot\]/i,
  /\[Claude\]/i,
  /\[Cursor\]/i,
  /\[ChatGPT\]/i,
  /\[Cody\]/i,
  /\[Aider\]/i,
  /\[Tabnine\]/i,

  /🤖/,
  /🧠.*generat/i,

  /^aider:/i,
];

const PR_BODY_PATTERNS = [
  new RegExp(`co[- ]?authored[- ]?(by)?[:\\s]*(${AI_TOOLS_PATTERN})`, "i"),
  /co[- ]?authored[- ]?(by)?[:\s]*(@anthropic\.com|@openai\.com|@cursor\.com)/i,
  new RegExp(
    `co[- ]?author[:\\s]*(?:(${AI_TOOLS_PATTERN})|AI|GenAI|LLM|@anthropic\\.com|@openai\\.com|@cursor\\.com)`,
    "i"
  ),

  new RegExp(`^\\s*(${AI_TOOLS_PATTERN})\\s*$`, "im"),
  new RegExp(`(by|with|via|from|using)\\s+(${AI_TOOLS_PATTERN})`, "i"),
  new RegExp(
    `(${AI_TOOLS_PATTERN})\\s+(by|with|via|from|helped|assisted|generated|wrote|created)`,
    "i"
  ),

  new RegExp(
    `\\b(generated|assisted|created|written|coded|implemented)\\s+(by|with|using|via)\\s+(${AI_TOOLS_PATTERN}|AI|GenAI|LLM)`,
    "i"
  ),
  new RegExp(
    `(${AI_TOOLS_PATTERN})\\s+(helped|assisted|generated|wrote|created)`,
    "i"
  ),

  /AI[- ]?(assisted|generated|powered|driven|authored|written|created)/i,
  /LLM[- ]?(assisted|generated|powered)/i,

  new RegExp(`using\\s+(${AI_TOOLS_PATTERN})`, "i"),
  new RegExp(`with\\s+(help\\s+)?(from|of)?\\s*(${AI_TOOLS_PATTERN}|AI)`, "i"),
  new RegExp(`via\\s+(${AI_TOOLS_PATTERN}|AI)`, "i"),
  new RegExp(
    `pair[- ]?programm(ing|ed)\\s+with\\s+(${AI_TOOLS_PATTERN}|AI)`,
    "i"
  ),

  /\[Claude Code\]/i,
  /\[GitHub Copilot\]/i,
  /claude\.ai/i,
  /cursor\.com/i,
  /anthropic\.com/i,

  /Generated with \[Claude Code\]/i,
];

const COMMENT_PATTERNS = [
  /This (PR|pull request|commit) was (generated|created|written) (by|with|using)/i,
  /Automated (by|via|using)/i,

  new RegExp(`I used (${AI_TOOLS_PATTERN}|AI)`, "i"),
  new RegExp(
    `(${AI_TOOLS_PATTERN}|AI)\\s+(suggested|recommended|generated|wrote)\\s+this`,
    "i"
  ),
  new RegExp(
    `pair[- ]?programm(ing|ed)\\s+with\\s+(${AI_TOOLS_PATTERN}|AI)`,
    "i"
  ),
];

const AI_LABELS = [
  "ai-assisted",
  "ai-generated",
  "genai",
  "genai-assisted",
  "llm-assisted",
  "llm-generated",
  "ai",
  "ai-automated",
  "auto-generated",
  "claude",
  "claude-assisted",
  "claude-generated",
  "copilot",
  "copilot-assisted",
  "github-copilot",
  "chatgpt",
  "chatgpt-assisted",
  "openai",
  "cursor",
  "cursor-assisted",
  "cody",
  "cody-assisted",
  "tabnine",
  "gemini",
];

const GENAI_LABEL = "genai-assisted";
const GENAI_LABEL_COLOR = "FEF3C7"; // #FEF3C7
const GENAI_LABEL_DESCRIPTION = "PR assisted by GenAI tools";

const AI_BRANCH_PREFIXES = [
  /^cursor\//i,
  /^claude\//i,
  /^ai\//i,
  /^copilot\//i,
  /^aider\//i,
  /^cody\//i,
  /^chatgpt\//i,
  /^genai\//i,
  /^windsurf\//i,
  /^devin\//i,
];

module.exports = {
  AI_TOOLS,
  AI_TOOLS_PATTERN,
  AI_DOMAINS,
  GENAI_BOT_PATTERNS,
  AUTOMATION_BOT_PATTERNS,
  COMMIT_PATTERNS,
  PR_BODY_PATTERNS,
  COMMENT_PATTERNS,
  AI_LABELS,
  GENAI_LABEL,
  GENAI_LABEL_COLOR,
  GENAI_LABEL_DESCRIPTION,
  AI_BRANCH_PREFIXES,
};
