const {
  matchesAnyPattern,
  isBot,
  hasAILabel,
  hasGenAILabel,
} = require("./genaiDetection");

const {
  BOT_PATTERNS,
  COMMIT_PATTERNS,
  PR_BODY_PATTERNS,
  COMMENT_PATTERNS,
} = require("./genaiPatterns");

describe("genaiDetection", () => {
  describe("isBot", () => {
    test.each([
      "github-actions[bot]",
      "dependabot[bot]",
      "renovate[bot]",
      "copilot[bot]",
      "semantic-release-bot",
      "snyk-bot",
      "netlify[bot]",
      "vercel[bot]",
      "mergify[bot]",
      "my-custom-bot",
      "bot-runner",
    ])("should detect bot: %s", (author) => {
      expect(isBot(author)).not.toBeNull();
    });

    test.each([
      "johndoe",
      "alice",
      "dev-team",
      "robotics-fan",
      "bottleneck",
      "about",
    ])("should NOT detect as bot: %s", (author) => {
      expect(isBot(author)).toBeNull();
    });
  });

  describe("hasAILabel", () => {
    test.each([
      [{ name: "ai-assisted" }],
      [{ name: "genai" }],
      [{ name: "claude" }],
      [{ name: "copilot" }],
      [{ name: "chatgpt" }],
      [{ name: "AI-ASSISTED" }], // case insensitive
      [{ name: "dependabot" }],
    ])("should detect AI label: %s", (label) => {
      expect(hasAILabel([label])).not.toBeNull();
    });

    test.each([
      [{ name: "bug" }],
      [{ name: "enhancement" }],
      [{ name: "feature" }],
      [{ name: "documentation" }],
    ])("should NOT detect as AI label: %s", (label) => {
      expect(hasAILabel([label])).toBeNull();
    });
  });

  describe("hasGenAILabel", () => {
    test("should return true when genai-assisted label exists", () => {
      expect(hasGenAILabel([{ name: "genai-assisted" }])).toBe(true);
      expect(hasGenAILabel([{ name: "GENAI-ASSISTED" }])).toBe(true);
    });

    test("should return false when genai-assisted label does not exist", () => {
      expect(hasGenAILabel([{ name: "bug" }])).toBe(false);
      expect(hasGenAILabel([{ name: "ai-assisted" }])).toBe(false);
      expect(hasGenAILabel([])).toBe(false);
      expect(hasGenAILabel(null)).toBe(false);
    });
  });

  describe("COMMIT_PATTERNS", () => {
    test.each([
      "feat: add login\n\n🤖 Generated with [Claude Code](https://claude.ai/code)",
      "fix: bug fix\n\nCo-Authored-By: Claude <noreply@anthropic.com>",
      "chore: update deps\n\nCo-Authored-By: Claude Opus 4.5 <noreply@anthropic.com>",
      "[AI] feat: new feature",
      "[Copilot] fix: typo",
      "[Claude] refactor: cleanup",
      "[ChatGPT] docs: update readme",
      "[Aider] fix: bug",
      "Generated with Claude Code",
      "feat: something 🤖",
      "aider: fix typo in main.js",
    ])("should match commit message: %s", (message) => {
      expect(matchesAnyPattern(message, COMMIT_PATTERNS)).not.toBeNull();
    });

    test.each([
      "feat: add login feature",
      "fix: resolve bug in authentication",
      "chore: update dependencies",
      "docs: improve documentation",
      "refactor: cleanup code",
      "Co-Authored-By: John Doe <john@example.com>",
    ])("should NOT match commit message: %s", (message) => {
      expect(matchesAnyPattern(message, COMMIT_PATTERNS)).toBeNull();
    });
  });

  describe("PR_BODY_PATTERNS", () => {
    test.each([
      "This PR was generated with Claude",
      "Code written by ChatGPT",
      "AI-assisted implementation",
      "AI-generated code",
      "Created using Copilot",
      "Implemented with help from Claude",
      "Pair programming with Cursor",
      "Claude helped write this",
      "Copilot assisted with this feature",
      "Generated with [Claude Code](https://claude.ai/code)",
      "Using Aider for this fix",
      "LLM-assisted refactoring",
    ])("should match PR body: %s", (body) => {
      expect(matchesAnyPattern(body, PR_BODY_PATTERNS)).not.toBeNull();
    });

    test.each([
      "This PR adds a new feature",
      "Fixed the login bug",
      "Updated documentation",
      "Refactored the auth module",
      "Added tests for the API",
    ])("should NOT match PR body: %s", (body) => {
      expect(matchesAnyPattern(body, PR_BODY_PATTERNS)).toBeNull();
    });
  });

  describe("COMMENT_PATTERNS", () => {
    test.each([
      "I used Claude to help with this",
      "ChatGPT suggested this approach",
      "Copilot generated this code",
      "This PR was generated by AI",
      "Automated by GitHub Actions",
      "Pair programming with Claude",
      "AI wrote this function",
    ])("should match comment: %s", (comment) => {
      expect(matchesAnyPattern(comment, COMMENT_PATTERNS)).not.toBeNull();
    });

    test.each([
      "Looks good to me!",
      "Please fix the typo on line 42",
      "Can you add more tests?",
      "Nice work on this feature",
    ])("should NOT match comment: %s", (comment) => {
      expect(matchesAnyPattern(comment, COMMENT_PATTERNS)).toBeNull();
    });
  });
});
