/**
 * GenAI Detection Patterns
 *
 * Exhaustive list of patterns to detect AI-assisted code in PRs.
 * Add new tools/patterns here as they emerge.
 */

// List of known AI coding tools and assistants
const AI_TOOLS = [
  // Anthropic
  "Claude",
  "Claude Code",
  "Claude Opus",
  "Claude Sonnet",
  "Anthropic",

  // OpenAI
  "ChatGPT",
  "GPT-4",
  "GPT-4o",
  "GPT-3",
  "OpenAI",
  "Codex",
  "o1",
  "o3",

  // GitHub
  "Copilot",
  "GitHub Copilot",
  "Copilot Chat",
  "Copilot Workspace",

  // Google
  "Gemini",
  "Gemini Code Assist",
  "Bard",
  "Google AI",
  "Duet AI",

  // IDE-based
  "Cursor",
  "Windsurf",
  "Codeium",
  "Continue",
  "Continue.dev",

  // Enterprise/Privacy-focused
  "Tabnine",
  "Augment",
  "Augment Code",
  "Sourcegraph Cody",
  "Cody",

  // JetBrains
  "JetBrains AI",
  "AI Assistant",

  // CLI/Agents
  "Aider",
  "Cline",
  "Claude Engineer",
  "GPT Engineer",
  "Devin",
  "Auto-GPT",
  "AutoGPT",
  "AgentGPT",
  "BabyAGI",
  "MetaGPT",

  // Code generation
  "CodeGPT",
  "CodeWhisperer",
  "Amazon Q",
  "Replit AI",
  "Ghostwriter",
  "Codey",
  "StarCoder",
  "Code Llama",
  "CodeLlama",
  "WizardCoder",
  "Phind",
  "Blackbox AI",
  "AskCodi",

  // Other
  "Perplexity",
  "Mistral",
  "LLM",
];

// Build a regex pattern from tools list (escaped for regex)
const escapeRegex = (str) => str.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
const AI_TOOLS_PATTERN = AI_TOOLS.map(escapeRegex).join("|");

// AI-related email domains
const AI_DOMAINS = [
  "@anthropic.com",
  "@openai.com",
  "noreply@github.com", // Used by Copilot
];

// Bot patterns for author detection
const BOT_PATTERNS = [
  // GitHub bots
  /github-actions\[bot\]/i,
  /copilot\[bot\]/i,
  /dependabot\[bot\]/i,
  /renovate\[bot\]/i,
  /semantic-release-bot/i,
  /greenkeeper\[bot\]/i,
  /snyk-bot/i,
  /codecov\[bot\]/i,
  /netlify\[bot\]/i,
  /vercel\[bot\]/i,
  /allcontributors\[bot\]/i,
  /imgbot\[bot\]/i,
  /mergify\[bot\]/i,
  /stale\[bot\]/i,
  /pull\[bot\]/i,

  // Generic bot patterns
  /\[bot\]$/i,
  /-bot$/i,
  /^bot-/i,
];

// Commit message patterns
const COMMIT_PATTERNS = [
  // Claude signatures
  /Generated with Claude Code/i,
  new RegExp(`🤖\\s*Generated with \\[Claude Code\\]`, "i"),
  /Co-Authored-By:.*Claude/i,
  /Co-Authored-By:.*@anthropic\.com/i,

  // Generic AI signatures
  /Generated by (AI|LLM)/i,
  /AI-generated/i,
  /\[AI\]/i,
  /\[GenAI\]/i,

  // Tool-specific signatures
  /\[Copilot\]/i,
  /\[Claude\]/i,
  /\[Cursor\]/i,
  /\[ChatGPT\]/i,
  /\[Cody\]/i,
  /\[Aider\]/i,
  /\[Tabnine\]/i,

  // Emoji indicators
  /🤖/,
  /🧠.*generat/i,

  // Aider specific
  /^aider:/i,

  // Co-authored-by with AI tools
  new RegExp(`Co-Authored-By:.*\\b(${AI_TOOLS_PATTERN})\\b`, "i"),

  // Co-authored-by with AI domains
  /Co-Authored-By:.*(@anthropic\.com|@openai\.com|noreply@github\.com)/i,
];

// PR body/description patterns
const PR_BODY_PATTERNS = [
  // Explicit assistance mentions
  new RegExp(
    `\\b(generated|assisted|created|written|coded|implemented)\\s+(by|with|using|via)\\s+(${AI_TOOLS_PATTERN}|AI|GenAI|LLM)`,
    "i"
  ),
  new RegExp(
    `(${AI_TOOLS_PATTERN})\\s+(helped|assisted|generated|wrote|created)`,
    "i"
  ),

  // AI-prefixed terms
  /AI-?(assisted|generated|powered|driven|authored|written|created)/i,
  /LLM-?(assisted|generated|powered)/i,

  // Tool mentions in context
  new RegExp(`using\\s+(${AI_TOOLS_PATTERN})`, "i"),
  new RegExp(`with\\s+help\\s+(from|of)\\s+(${AI_TOOLS_PATTERN}|AI)`, "i"),
  new RegExp(`via\\s+(${AI_TOOLS_PATTERN}|AI)`, "i"),
  new RegExp(`pair[- ]?programm(ing|ed)\\s+with\\s+(${AI_TOOLS_PATTERN}|AI)`, "i"),

  // Markdown badges/links
  /\[Claude Code\]/i,
  /\[GitHub Copilot\]/i,
  /claude\.ai\/code/i,
  /cursor\.com/i,

  // Claude Code signature in PR body
  /Generated with \[Claude Code\]/i,
];

// PR comment patterns
const COMMENT_PATTERNS = [
  // Bot comments
  /This (PR|pull request|commit) was (generated|created|written) (by|with|using)/i,
  /Automated (by|via|using)/i,

  // User mentions of AI usage
  new RegExp(`I used (${AI_TOOLS_PATTERN}|AI)`, "i"),
  new RegExp(
    `(${AI_TOOLS_PATTERN}|AI)\\s+(suggested|recommended|generated|wrote)\\s+this`,
    "i"
  ),
  new RegExp(`pair[- ]?programm(ing|ed)\\s+with\\s+(${AI_TOOLS_PATTERN}|AI)`, "i"),
];

// Labels that indicate AI assistance
const AI_LABELS = [
  // Generic
  "ai-assisted",
  "ai-generated",
  "genai",
  "genai-assisted",
  "llm-assisted",
  "llm-generated",
  "ai",
  "artificial-intelligence",
  "automated",
  "auto-generated",

  // Tool-specific
  "claude",
  "claude-assisted",
  "claude-generated",
  "copilot",
  "copilot-assisted",
  "github-copilot",
  "chatgpt",
  "chatgpt-assisted",
  "openai",
  "cursor",
  "cursor-assisted",
  "cody",
  "cody-assisted",
  "tabnine",
  "gemini",
  "aider",

  // Bot labels
  "bot",
  "dependabot",
  "renovate",
];

// The label we apply when GenAI is detected
const GENAI_LABEL = "genai-assisted";

// AI config files that indicate AI tool usage
const AI_CONFIG_FILES = [
  // Claude
  /^CLAUDE\.md$/i,
  /^\.claude\//,
  /^\.claude$/,

  // Cursor
  /^\.cursorrules$/,
  /^\.cursor\//,
  /^\.cursorignore$/,

  // Continue
  /^\.continue\//,
  /^\.continuerc/,

  // Aider
  /^\.aider/,
  /^\.aiderignore$/,

  // Copilot
  /^\.github\/copilot-instructions\.md$/,
  /copilot-instructions\.md$/,

  // Cody
  /^\.cody\//,

  // Windsurf
  /^\.windsurf\//,
  /^\.windsurfrules$/,

  // Generic
  /^\.ai\//,
  /^ai-instructions\.md$/i,
];

// Branch prefixes that indicate AI tool usage
const AI_BRANCH_PREFIXES = [
  /^cursor\//i,
  /^claude\//i,
  /^ai\//i,
  /^copilot\//i,
  /^aider\//i,
  /^cody\//i,
  /^chatgpt\//i,
  /^genai\//i,
  /^windsurf\//i,
  /^devin\//i,
];

module.exports = {
  AI_TOOLS,
  AI_TOOLS_PATTERN,
  AI_DOMAINS,
  BOT_PATTERNS,
  COMMIT_PATTERNS,
  PR_BODY_PATTERNS,
  COMMENT_PATTERNS,
  AI_LABELS,
  GENAI_LABEL,
  AI_CONFIG_FILES,
  AI_BRANCH_PREFIXES,
};
