const AI_TOOLS = [
  "Claude",
  "Claude Code",
  "Claude Opus",
  "Claude Sonnet",
  "Anthropic",

  "ChatGPT",
  "GPT-4",
  "GPT-4o",
  "GPT-3",
  "OpenAI",
  "Codex",
  "o1",
  "o3",

  "Copilot",
  "GitHub Copilot",
  "Copilot Chat",
  "Copilot Workspace",

  "Gemini",
  "Gemini Code Assist",
  "Bard",
  "Google AI",
  "Duet AI",

  "Cursor",
  "Windsurf",
  "Codeium",
  "Continue",
  "Continue.dev",

  "Tabnine",
  "Augment",
  "Augment Code",
  "Sourcegraph Cody",
  "Cody",

  "JetBrains AI",
  "AI Assistant",

  "Aider",
  "Cline",
  "Claude Engineer",
  "GPT Engineer",
  "Devin",
  "Auto-GPT",
  "AutoGPT",
  "AgentGPT",
  "BabyAGI",
  "MetaGPT",

  "CodeGPT",
  "CodeWhisperer",
  "Amazon Q",
  "Replit AI",
  "Ghostwriter",
  "Codey",
  "StarCoder",
  "Code Llama",
  "CodeLlama",
  "WizardCoder",
  "Phind",
  "Blackbox AI",
  "AskCodi",

  "Perplexity",
];

// Build a regex pattern from tools list (escaped for regex)
const escapeRegex = (str) => str.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
const escapeRegex = (str) => str.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
const AI_TOOLS_PATTERN = AI_TOOLS.map(escapeRegex).join("|");

const AI_DOMAINS = [
  "@anthropic.com",
  "@openai.com",

];

const BOT_PATTERNS = [
  /github-actions\[bot\]/i,
  /copilot\[bot\]/i,
  /dependabot\[bot\]/i,
  /renovate\[bot\]/i,
  /semantic-release-bot/i,
  /greenkeeper\[bot\]/i,
  /snyk-bot/i,
  /codecov\[bot\]/i,
  /netlify\[bot\]/i,
  /vercel\[bot\]/i,
  /allcontributors\[bot\]/i,
  /imgbot\[bot\]/i,
  /mergify\[bot\]/i,
  /stale\[bot\]/i,
  /pull\[bot\]/i,

  /\[bot\]$/i,
  /[\[\-]bot$/i,
  /^bot[\-\[]/i,
];

const COMMIT_PATTERNS = [
  /Generated with Claude Code/i,
  new RegExp(`🤖\\s*Generated with \\[Claude Code\\]`, "i"),
  /Co-Authored-By:.*Claude/i,
  /Co-Authored-By:.*@anthropic\.com/i,

  /Generated by (AI|LLM)/i,
  /AI-generated/i,
  /\[AI\]/i,
  /\[GenAI\]/i,

  /\[Copilot\]/i,
  /\[Claude\]/i,
  /\[Cursor\]/i,
  /\[ChatGPT\]/i,
  /\[Cody\]/i,
  /\[Aider\]/i,
  /\[Tabnine\]/i,

  /🤖/,
  /🧠.*generat/i,

  /^aider:/i,

  new RegExp(`Co-Authored-By:.*\\b(${AI_TOOLS_PATTERN})\\b`, "i"),

  /Co-Authored-By:.*(@anthropic\.com|@openai\.com|noreply@github\.com)/i,
];

const PR_BODY_PATTERNS = [
  new RegExp(`co[- ]?authored[- ]?(by)?[:\\s]*(${AI_TOOLS_PATTERN})`, "i"),
  /co[- ]?authored[- ]?(by)?[:\s]*(@anthropic\.com|@openai\.com|noreply@github\.com)/i,
  /co[- ]?author[:\s]/i, // Very broad - any "co-author:" mention

  new RegExp(`^\\s*(${AI_TOOLS_PATTERN})\\s*$`, "im"), // Tool name alone on a line
  new RegExp(`(by|with|via|from|using)\\s+(${AI_TOOLS_PATTERN})`, "i"),
  new RegExp(
    `(${AI_TOOLS_PATTERN})\\s+(by|with|via|from|helped|assisted|generated|wrote|created)`,
    "i"
  ),

  new RegExp(
    `\\b(generated|assisted|created|written|coded|implemented)\\s+(by|with|using|via)\\s+(${AI_TOOLS_PATTERN}|AI|GenAI|LLM)`,
    "i"
  ),
  new RegExp(
    `(${AI_TOOLS_PATTERN})\\s+(helped|assisted|generated|wrote|created)`,
    "i"
  ),

  /AI[- ]?(assisted|generated|powered|driven|authored|written|created)/i,
  /LLM[- ]?(assisted|generated|powered)/i,

  new RegExp(`using\\s+(${AI_TOOLS_PATTERN})`, "i"),
  new RegExp(`with\\s+(help\\s+)?(from|of)?\\s*(${AI_TOOLS_PATTERN}|AI)`, "i"),
  new RegExp(`via\\s+(${AI_TOOLS_PATTERN}|AI)`, "i"),
  new RegExp(
    `pair[- ]?programm(ing|ed)\\s+with\\s+(${AI_TOOLS_PATTERN}|AI)`,
    "i"
  ),

  /\[Claude Code\]/i,
  /\[GitHub Copilot\]/i,
  /claude\.ai/i,
  /cursor\.com/i,
  /anthropic\.com/i,

  /Generated with \[Claude Code\]/i,

  new RegExp(`\\b(${AI_TOOLS_PATTERN})\\b`, "i"),
];

const COMMENT_PATTERNS = [
  /This (PR|pull request|commit) was (generated|created|written) (by|with|using)/i,
  /Automated (by|via|using)/i,

  new RegExp(`I used (${AI_TOOLS_PATTERN}|AI)`, "i"),
  new RegExp(
    `(${AI_TOOLS_PATTERN}|AI)\\s+(suggested|recommended|generated|wrote)\\s+this`,
    "i"
  ),
  new RegExp(
    `pair[- ]?programm(ing|ed)\\s+with\\s+(${AI_TOOLS_PATTERN}|AI)`,
    "i"
  ),
];

const AI_LABELS = [
  "ai-assisted",
  "ai-generated",
  "genai",
  "genai-assisted",
  "llm-assisted",
  "llm-generated",
  "ai",
  "artificial-intelligence",
  "automated",
  "auto-generated",

  "claude",
  "claude-assisted",
  "claude-generated",
  "copilot",
  "copilot-assisted",
  "github-copilot",
  "chatgpt",
  "chatgpt-assisted",
  "openai",
  "cursor",
  "cursor-assisted",
  "cody",
  "cody-assisted",
  "tabnine",
  "gemini",
  "aider",

  "bot",
  "dependabot",
  "renovate",
];

const GENAI_LABEL = "genai-assisted";

const AI_CONFIG_FILES = [
  /^CLAUDE\.md$/i,
  /^\.claude\//,
  /^\.claude$/,

  /^\.cursorrules$/,
  /^\.cursor\//,
  /^\.cursorignore$/,

  /^\.continue\//,
  /^\.continuerc/,

  /^\.aider/,
  /^\.aiderignore$/,

  /^\.github\/copilot-instructions\.md$/,
  /copilot-instructions\.md$/,

  /^\.cody\//,

  /^\.windsurf\//,
  /^\.windsurfrules$/,

  /^\.ai\//,
  /^ai-instructions\.md$/i,
];

const AI_BRANCH_PREFIXES = [
  /^cursor\//i,
  /^claude\//i,
  /^ai\//i,
  /^copilot\//i,
  /^aider\//i,
  /^cody\//i,
  /^chatgpt\//i,
  /^genai\//i,
  /^windsurf\//i,
  /^devin\//i,
];

module.exports = {
  AI_TOOLS,
  AI_TOOLS_PATTERN,
  AI_DOMAINS,
  BOT_PATTERNS,
  COMMIT_PATTERNS,
  PR_BODY_PATTERNS,
  COMMENT_PATTERNS,
  AI_LABELS,
  GENAI_LABEL,
  AI_CONFIG_FILES,
  AI_BRANCH_PREFIXES,
};
