const {
  matchesAnyPattern,
  isBot,
  hasAILabel,
  hasGenAILabel,
  hasAIBranchPrefix,
  isAIConfigFile,
  hasRapidCommits,
  detectGenAI,
} = require("./genaiDetection");

const {
  BOT_PATTERNS,
  COMMIT_PATTERNS,
  PR_BODY_PATTERNS,
  COMMENT_PATTERNS,
} = require("./genaiPatterns");

describe("genaiDetection", () => {
  describe("isBot", () => {
    test.each([
      "github-actions[bot]",
      "dependabot[bot]",
      "renovate[bot]",
      "copilot[bot]",
      "semantic-release-bot",
      "snyk-bot",
      "netlify[bot]",
      "vercel[bot]",
      "mergify[bot]",
      "my-custom-bot",
      "bot-runner",
    ])("should detect bot: %s", (author) => {
      expect(isBot(author)).not.toBeNull();
    });

    test.each([
      "johndoe",
      "alice",
      "dev-team",
      "robotics-fan",
      "bottleneck",
      "about",
    ])("should NOT detect as bot: %s", (author) => {
      expect(isBot(author)).toBeNull();
    });
  });

  describe("hasAILabel", () => {
    test.each([
      [{ name: "ai-assisted" }],
      [{ name: "genai" }],
      [{ name: "claude" }],
      [{ name: "copilot" }],
      [{ name: "chatgpt" }],
      [{ name: "AI-ASSISTED" }], // case insensitive
      [{ name: "dependabot" }],
    ])("should detect AI label: %s", (label) => {
      expect(hasAILabel([label])).not.toBeNull();
    });

    test.each([
      [{ name: "bug" }],
      [{ name: "enhancement" }],
      [{ name: "feature" }],
      [{ name: "documentation" }],
    ])("should NOT detect as AI label: %s", (label) => {
      expect(hasAILabel([label])).toBeNull();
    });
  });

  describe("hasGenAILabel", () => {
    test("should return true when genai-assisted label exists", () => {
      expect(hasGenAILabel([{ name: "genai-assisted" }])).toBe(true);
      expect(hasGenAILabel([{ name: "GENAI-ASSISTED" }])).toBe(true);
    });

    test("should return false when genai-assisted label does not exist", () => {
      expect(hasGenAILabel([{ name: "bug" }])).toBe(false);
      expect(hasGenAILabel([{ name: "ai-assisted" }])).toBe(false);
      expect(hasGenAILabel([])).toBe(false);
      expect(hasGenAILabel(null)).toBe(false);
    });
  });

  describe("COMMIT_PATTERNS", () => {
    test.each([
      "feat: add login\n\n🤖 Generated with [Claude Code](https://claude.ai/code)",
      "fix: bug fix\n\nCo-Authored-By: Claude <noreply@anthropic.com>",
      "chore: update deps\n\nCo-Authored-By: Claude Opus 4.5 <noreply@anthropic.com>",
      "[AI] feat: new feature",
      "[Copilot] fix: typo",
      "[Claude] refactor: cleanup",
      "[ChatGPT] docs: update readme",
      "[Aider] fix: bug",
      "Generated with Claude Code",
      "feat: something 🤖",
      "aider: fix typo in main.js",
    ])("should match commit message: %s", (message) => {
      expect(matchesAnyPattern(message, COMMIT_PATTERNS)).not.toBeNull();
    });

    test.each([
      "feat: add login feature",
      "fix: resolve bug in authentication",
      "chore: update dependencies",
      "docs: improve documentation",
      "refactor: cleanup code",
      "Co-Authored-By: John Doe <john@example.com>",
    ])("should NOT match commit message: %s", (message) => {
      expect(matchesAnyPattern(message, COMMIT_PATTERNS)).toBeNull();
    });
  });

  describe("PR_BODY_PATTERNS", () => {
    test.each([
      "This PR was generated with Claude",
      "Code written by ChatGPT",
      "AI-assisted implementation",
      "AI-generated code",
      "Created using Copilot",
      "Implemented with help from Claude",
      "Pair programming with Cursor",
      "Claude helped write this",
      "Copilot assisted with this feature",
      "Generated with [Claude Code](https://claude.ai/code)",
      "Using Aider for this fix",
      "LLM-assisted refactoring",
    ])("should match PR body: %s", (body) => {
      expect(matchesAnyPattern(body, PR_BODY_PATTERNS)).not.toBeNull();
    });

    test.each([
      "This PR adds a new feature",
      "Fixed the login bug",
      "Updated documentation",
      "Refactored the auth module",
      "Added tests for the API",
    ])("should NOT match PR body: %s", (body) => {
      expect(matchesAnyPattern(body, PR_BODY_PATTERNS)).toBeNull();
    });
  });

  describe("COMMENT_PATTERNS", () => {
    test.each([
      "I used Claude to help with this",
      "ChatGPT suggested this approach",
      "Copilot generated this code",
      "This PR was generated by AI",
      "Automated by GitHub Actions",
      "Pair programming with Claude",
      "AI wrote this function",
    ])("should match comment: %s", (comment) => {
      expect(matchesAnyPattern(comment, COMMENT_PATTERNS)).not.toBeNull();
    });

    test.each([
      "Looks good to me!",
      "Please fix the typo on line 42",
      "Can you add more tests?",
      "Nice work on this feature",
    ])("should NOT match comment: %s", (comment) => {
      expect(matchesAnyPattern(comment, COMMENT_PATTERNS)).toBeNull();
    });
  });

  describe("hasAIBranchPrefix", () => {
    test.each([
      "cursor/add-feature",
      "claude/fix-bug",
      "ai/new-component",
      "copilot/refactor",
      "aider/update-deps",
      "cody/docs",
      "chatgpt/experiment",
      "genai/test",
      "windsurf/style",
      "devin/automation",
      "CURSOR/uppercase", // case insensitive
    ])("should detect AI branch prefix: %s", (branch) => {
      expect(hasAIBranchPrefix(branch)).not.toBeNull();
    });

    test.each([
      "feat/add-feature",
      "fix/bug-fix",
      "chore/update-deps",
      "docs/readme",
      "refactor/cleanup",
      "test/add-tests",
      "hotfix/urgent",
      "feature/cursor-support", // cursor not at start
      "my-cursor-branch",
    ])("should NOT detect AI branch prefix: %s", (branch) => {
      expect(hasAIBranchPrefix(branch)).toBeNull();
    });
  });

  describe("isAIConfigFile", () => {
    test.each([
      "CLAUDE.md",
      "claude.md",
      ".claude/config.json",
      ".cursorrules",
      ".cursor/settings.json",
      ".cursorignore",
      ".continue/config.json",
      ".continuerc",
      ".aider.conf",
      ".aiderignore",
      ".github/copilot-instructions.md",
      "copilot-instructions.md",
      ".cody/config.json",
      ".windsurf/settings.json",
      ".windsurfrules",
      ".ai/config.json",
      "ai-instructions.md",
    ])("should detect AI config file: %s", (file) => {
      expect(isAIConfigFile(file)).not.toBeNull();
    });

    test.each([
      "README.md",
      "package.json",
      "src/index.js",
      "src/claude.js", // claude in path but not config
      ".gitignore",
      ".eslintrc.js",
      "docs/cursor.md", // cursor in path but not config
      "config/ai.json", // ai in path but not .ai/ directory
    ])("should NOT detect AI config file: %s", (file) => {
      expect(isAIConfigFile(file)).toBeNull();
    });
  });

  describe("hasRapidCommits", () => {
    const makeCommit = (sha, dateStr) => ({
      sha,
      commit: { author: { date: dateStr } },
    });

    test("should detect rapid commits (3+ within 30 seconds)", () => {
      const commits = [
        makeCommit("abc1234", "2024-01-01T10:00:00Z"),
        makeCommit("def5678", "2024-01-01T10:00:10Z"), // 10 sec later
        makeCommit("ghi9012", "2024-01-01T10:00:20Z"), // 10 sec later
      ];
      const result = hasRapidCommits(commits);
      expect(result.detected).toBe(true);
      expect(result.details).toContain("commits within 30 seconds");
    });

    test("should detect rapid commits with 4 fast commits", () => {
      const commits = [
        makeCommit("abc1234", "2024-01-01T10:00:00Z"),
        makeCommit("def5678", "2024-01-01T10:00:05Z"),
        makeCommit("ghi9012", "2024-01-01T10:00:10Z"),
        makeCommit("jkl3456", "2024-01-01T10:00:15Z"),
      ];
      const result = hasRapidCommits(commits);
      expect(result.detected).toBe(true);
    });

    test("should NOT detect when commits are spaced out", () => {
      const commits = [
        makeCommit("abc1234", "2024-01-01T10:00:00Z"),
        makeCommit("def5678", "2024-01-01T10:05:00Z"), // 5 min later
        makeCommit("ghi9012", "2024-01-01T10:10:00Z"), // 5 min later
      ];
      const result = hasRapidCommits(commits);
      expect(result.detected).toBe(false);
    });

    test("should NOT detect with less than 3 commits", () => {
      const commits = [
        makeCommit("abc1234", "2024-01-01T10:00:00Z"),
        makeCommit("def5678", "2024-01-01T10:00:05Z"),
      ];
      const result = hasRapidCommits(commits);
      expect(result.detected).toBe(false);
    });

    test("should NOT detect with only 2 rapid commits out of 3", () => {
      const commits = [
        makeCommit("abc1234", "2024-01-01T10:00:00Z"),
        makeCommit("def5678", "2024-01-01T10:00:10Z"), // 10 sec later (rapid)
        makeCommit("ghi9012", "2024-01-01T10:05:00Z"), // 5 min later (not rapid)
      ];
      const result = hasRapidCommits(commits);
      expect(result.detected).toBe(false);
    });

    test("should handle empty or null commits", () => {
      expect(hasRapidCommits([])).toEqual({ detected: false, details: null });
      expect(hasRapidCommits(null)).toEqual({ detected: false, details: null });
    });
  });

  describe("detectGenAI", () => {
    const mockOctokit = {
      paginate: jest.fn(),
    };

    const basePullRequest = {
      user: { login: "johndoe" },
      head: { ref: "feat/my-feature" },
      body: "This is a normal PR",
      labels: [],
    };

    beforeEach(() => {
      jest.clearAllMocks();
      mockOctokit.paginate.mockResolvedValue([]);
    });

    test("should skip detection if already labeled with genai-assisted", async () => {
      const pullRequest = {
        ...basePullRequest,
        labels: [{ name: "genai-assisted" }],
      };

      const result = await detectGenAI(mockOctokit, {
        owner: "test",
        repo: "repo",
        pullNumber: 1,
        pullRequest,
      });

      expect(result.detected).toBe(false);
      expect(result.alreadyLabeled).toBe(true);
    });

    test("should detect bot author", async () => {
      const pullRequest = {
        ...basePullRequest,
        user: { login: "dependabot[bot]" },
      };

      const result = await detectGenAI(mockOctokit, {
        owner: "test",
        repo: "repo",
        pullNumber: 1,
        pullRequest,
      });

      expect(result.detected).toBe(true);
      expect(result.reason).toContain("bot pattern");
    });

    test("should detect AI branch prefix", async () => {
      const pullRequest = {
        ...basePullRequest,
        head: { ref: "claude/fix-bug" },
      };

      const result = await detectGenAI(mockOctokit, {
        owner: "test",
        repo: "repo",
        pullNumber: 1,
        pullRequest,
      });

      expect(result.detected).toBe(true);
      expect(result.reason).toContain("AI-related prefix");
    });

    test("should detect GenAI pattern in PR body", async () => {
      const pullRequest = {
        ...basePullRequest,
        body: "This PR was generated with Claude",
      };

      const result = await detectGenAI(mockOctokit, {
        owner: "test",
        repo: "repo",
        pullNumber: 1,
        pullRequest,
      });

      expect(result.detected).toBe(true);
      expect(result.reason).toContain("PR body matches GenAI pattern");
    });

    test("should detect existing AI label", async () => {
      const pullRequest = {
        ...basePullRequest,
        labels: [{ name: "copilot" }],
      };

      const result = await detectGenAI(mockOctokit, {
        owner: "test",
        repo: "repo",
        pullNumber: 1,
        pullRequest,
      });

      expect(result.detected).toBe(true);
      expect(result.reason).toContain("AI-related label");
    });

    test("should detect GenAI pattern in commit message", async () => {
      mockOctokit.paginate.mockImplementation((endpoint) => {
        if (endpoint.includes("commits")) {
          return Promise.resolve([
            {
              sha: "abc1234567890",
              commit: {
                message:
                  "feat: add feature\n\n🤖 Generated with [Claude Code](https://claude.ai/code)",
                author: { name: "johndoe", date: "2024-01-01T10:00:00Z" },
              },
              author: { login: "johndoe" },
              committer: { login: "johndoe" },
            },
          ]);
        }
        return Promise.resolve([]);
      });

      const result = await detectGenAI(mockOctokit, {
        owner: "test",
        repo: "repo",
        pullNumber: 1,
        pullRequest: basePullRequest,
      });

      expect(result.detected).toBe(true);
      expect(result.reason).toContain("commit");
      expect(result.reason).toContain("GenAI pattern");
    });

    test("should detect AI config file", async () => {
      mockOctokit.paginate.mockImplementation((endpoint) => {
        if (endpoint.includes("files")) {
          return Promise.resolve([{ filename: "CLAUDE.md" }]);
        }
        return Promise.resolve([]);
      });

      const result = await detectGenAI(mockOctokit, {
        owner: "test",
        repo: "repo",
        pullNumber: 1,
        pullRequest: basePullRequest,
      });

      expect(result.detected).toBe(true);
      expect(result.reason).toContain("AI config file");
    });

    test("should detect rapid commits", async () => {
      mockOctokit.paginate.mockImplementation((endpoint) => {
        if (endpoint.includes("commits")) {
          return Promise.resolve([
            {
              sha: "abc1234567890",
              commit: {
                message: "feat: add feature",
                author: { date: "2024-01-01T10:00:00Z" },
              },
              author: { login: "johndoe" },
              committer: { login: "johndoe" },
            },
            {
              sha: "def5678901234",
              commit: {
                message: "fix: typo",
                author: { date: "2024-01-01T10:00:10Z" },
              },
              author: { login: "johndoe" },
              committer: { login: "johndoe" },
            },
            {
              sha: "ghi9012345678",
              commit: {
                message: "chore: cleanup",
                author: { date: "2024-01-01T10:00:20Z" },
              },
              author: { login: "johndoe" },
              committer: { login: "johndoe" },
            },
          ]);
        }
        return Promise.resolve([]);
      });

      const result = await detectGenAI(mockOctokit, {
        owner: "test",
        repo: "repo",
        pullNumber: 1,
        pullRequest: basePullRequest,
      });

      expect(result.detected).toBe(true);
      expect(result.reason).toContain("Rapid commit timing");
    });

    test("should return false when no GenAI detected", async () => {
      const result = await detectGenAI(mockOctokit, {
        owner: "test",
        repo: "repo",
        pullNumber: 1,
        pullRequest: basePullRequest,
      });

      expect(result.detected).toBe(false);
      expect(result.reason).toBeNull();
    });

    test("should detect bot in commit author", async () => {
      mockOctokit.paginate.mockImplementation((endpoint) => {
        if (endpoint.includes("commits")) {
          return Promise.resolve([
            {
              sha: "abc1234567890",
              commit: {
                message: "chore: update deps",
                author: { name: "renovate[bot]", date: "2024-01-01T10:00:00Z" },
              },
              author: { login: "renovate[bot]" },
              committer: { login: "renovate[bot]" },
            },
          ]);
        }
        return Promise.resolve([]);
      });

      const result = await detectGenAI(mockOctokit, {
        owner: "test",
        repo: "repo",
        pullNumber: 1,
        pullRequest: basePullRequest,
      });

      expect(result.detected).toBe(true);
      expect(result.reason).toContain("bot pattern");
    });

    test("should detect bot in comment author", async () => {
      mockOctokit.paginate.mockImplementation((endpoint) => {
        if (endpoint.includes("comments")) {
          return Promise.resolve([
            {
              user: { login: "github-actions[bot]" },
              body: "Deployment successful",
            },
          ]);
        }
        return Promise.resolve([]);
      });

      const result = await detectGenAI(mockOctokit, {
        owner: "test",
        repo: "repo",
        pullNumber: 1,
        pullRequest: basePullRequest,
      });

      expect(result.detected).toBe(true);
      expect(result.reason).toContain("Comment author");
      expect(result.reason).toContain("bot pattern");
    });
  });
});
