name: Merge Housekeeping

on:
  pull_request:
    types: [closed]

jobs:
  ZapierReviewRequestedPurpleHeart:
    if: github.event.pull_request.merged == true
    name: "Zapier Purple Heart"
    runs-on: ubuntu-20.04
    timeout-minutes: 1
    steps:
      - name: "Sync emoji in #mobsuccess-review-requested"
        run: curl ${{ secrets.ZAPIER_REVIEW_REQUESTED_PURPLE_HEART }}?repo=${{ github.repository }}&pr=${{ github.event.number }} -D /dev/stderr -s

  ZapierReviewRequestedRedCross:
    if: github.event.pull_request.merged == false
    name: "Zapier Red Cross"
    runs-on: ubuntu-20.04
    timeout-minutes: 1
    steps:
      - name: "Sync emoji in #mobsuccess-review-requested"
        run: curl ${{ secrets.ZAPIER_REVIEW_REQUESTED_RED_CROSS }}?repo=${{ github.repository }}&pr=${{ github.event.number }} -D /dev/stderr -s
