name: Dockerfile

on:
  merge_group:
    types:
      - checks_requested
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - "**/Dockerfile*"
      - ".github/workflows/dockerfile.yml"
  push:
    branches:
      - master
      - prod
    paths:
      - "**/Dockerfile*"
      - ".github/workflows/dockerfile.yml"

jobs:
  dockerfile:
    name: Dockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Dockerfile lint
        uses: hadolint/hadolint-action@v3.3.0
        with:
          dockerfile: "Dockerfile*"
          recursive: true
          format: tty
          failure-threshold: warning
