name: Mobsuccess Compliance

on:
  pull_request:
    types:
      - opened
      - edited

jobs:
  MobsuccessPRCompliance:
    name: "Mobsuccess PR Compliance"
    runs-on: ubuntu-20.04
    steps:
      - uses: mobsuccess-devops/github-actions-mobsuccess@master
        with:
          github-token: ${{ github.token }}
          action: "validate-pr"
