name: Mobsuccess Compliance

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  MobsuccessPRCompliance:
    name: "Mobsuccess PR Compliance"
    runs-on: ubuntu-20.04
    timeout-minutes: 2
    steps:
      - uses: mobsuccess-devops/github-actions-mobsuccess@master
        with:
          github-token: ${{ github.token }}
          amplify-uri: ${{ secrets.AWS_AMPLIFY_URI }}
          storybook-amplify-uri: ${{ secrets.AWS_STORYBOOK_AMPLIFY_URI }}
          action: "validate-pr"
